# Generated by Django 3.1 on 2020-08-14 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtadminuser',
            name='contact_number',
            field=models.CharField(default='xxxxxxxxxx', max_length=50),
        ),
        migrations.AlterField(
            model_name='mtadminuser',
            name='first_name',
            field=models.CharField(default='first name', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtadminuser',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='mtadminuser',
            name='last_name',
            field=models.CharField(default='second name', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtadminuser',
            name='lost_password_code',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtadminuser',
            name='role',
            field=models.CharField(default='default', max_length=100),
        ),
        migrations.AlterField(
            model_name='mtadminuser',
            name='session_token',
            field=models.CharField(default='default', max_length=255),
        ),
        migrations.AlterField(
            model_name='mtadminuser',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='mtadminuser',
            name='user_access',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
